# Generated by Django 5.1.5 on 2025-02-06 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_age_profile_date_of_birth'),
        ('blog', '0004_comment_commenttranslation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttranslation',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_by_profile', to='accounts.profile'),
        ),
    ]
