# Generated by Django 5.1.5 on 2025-02-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_commenttranslation_name_comment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
